-- MySQL Script generated by MySQL Workbench
-- 02/07/15 11:01:38
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipo_pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_pregunta` (
  `codigo` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contexto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contexto` (
  `codigo` INT NOT NULL,
  `enunciado` VARCHAR(100) NOT NULL,
  `imagen` VARCHAR(100) NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `autor` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rol` (
  `codigo` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `codigo` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `rol` INT NOT NULL,
  `passwd` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_usuario_1_idx` (`rol` ASC),
  CONSTRAINT `fk_usuario_1`
    FOREIGN KEY (`rol`)
    REFERENCES `mydb`.`rol` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`grado_dificultad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`grado_dificultad` (
  `codigo` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`nivel_evaluativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`nivel_evaluativo` (
  `codigo` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `decripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pregunta` (
  `codigo` INT NOT NULL,
  `enunciado` VARCHAR(100) NOT NULL,
  `tipo` INT NOT NULL,
  `materia` INT NOT NULL,
  `habilitado` TINYINT(1) NOT NULL DEFAULT 1,
  `fecha_creacion` DATETIME NOT NULL,
  `contexto` INT NULL,
  `autor` INT NOT NULL,
  `grado_dificultad` INT NOT NULL,
  `imagen` VARCHAR(100) NULL,
  `nivel_evaluativo` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_pregunta_1_idx` (`tipo` ASC),
  INDEX `fk_pregunta_4_idx` (`contexto` ASC),
  INDEX `fk_pregunta_5_idx` (`autor` ASC),
  INDEX `fk_pregunta_6_idx` (`grado_dificultad` ASC),
  INDEX `fk_pregunta_2_idx` (`nivel_evaluativo` ASC),
  CONSTRAINT `fk_pregunta_1`
    FOREIGN KEY (`tipo`)
    REFERENCES `mydb`.`tipo_pregunta` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pregunta_4`
    FOREIGN KEY (`contexto`)
    REFERENCES `mydb`.`contexto` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pregunta_5`
    FOREIGN KEY (`autor`)
    REFERENCES `mydb`.`usuario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pregunta_6`
    FOREIGN KEY (`grado_dificultad`)
    REFERENCES `mydb`.`grado_dificultad` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pregunta_2`
    FOREIGN KEY (`nivel_evaluativo`)
    REFERENCES `mydb`.`nivel_evaluativo` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`respuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`respuesta` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `texto` VARCHAR(500) NOT NULL,
  `correcta` TINYINT(1) NOT NULL,
  `codigo_pregunta` INT NOT NULL,
  `imagen` VARCHAR(100) NULL,
  PRIMARY KEY (`codigo`, `codigo_pregunta`),
  INDEX `fk_respuesta_1_idx` (`codigo_pregunta` ASC),
  CONSTRAINT `fk_respuesta_1`
    FOREIGN KEY (`codigo_pregunta`)
    REFERENCES `mydb`.`pregunta` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`area_conocimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`area_conocimiento` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `area_padre` INT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_area_conocimiento_1_idx` (`area_padre` ASC),
  CONSTRAINT `fk_area_conocimiento_1`
    FOREIGN KEY (`area_padre`)
    REFERENCES `mydb`.`area_conocimiento` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cuestionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cuestionario` (
  `codigo` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `numero_preguntas` INT NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `autor` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_cuestionario_1_idx` (`autor` ASC),
  CONSTRAINT `fk_cuestionario_1`
    FOREIGN KEY (`autor`)
    REFERENCES `mydb`.`usuario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pregunta_x_cuestionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pregunta_x_cuestionario` (
  `codigo` INT NOT NULL,
  `cuestionario` INT NOT NULL,
  `pregunta` INT NOT NULL,
  `porcentaje` DOUBLE NOT NULL,
  `indice` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_pregunta_x_cuestionario_1_idx` (`cuestionario` ASC),
  INDEX `fk_pregunta_x_cuestionario_2_idx` (`pregunta` ASC),
  CONSTRAINT `fk_pregunta_x_cuestionario_1`
    FOREIGN KEY (`cuestionario`)
    REFERENCES `mydb`.`cuestionario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pregunta_x_cuestionario_2`
    FOREIGN KEY (`pregunta`)
    REFERENCES `mydb`.`pregunta` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`materia` (
  `codigo` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `area_conocimiento` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_materia_1_idx` (`area_conocimiento` ASC),
  CONSTRAINT `fk_materia_1`
    FOREIGN KEY (`area_conocimiento`)
    REFERENCES `mydb`.`area_conocimiento` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`grupo` (
  `codigo` INT NOT NULL,
  `materia` INT NOT NULL,
  `semestre` VARCHAR(45) NOT NULL,
  `profesor` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_grupo_1_idx` (`materia` ASC),
  INDEX `fk_grupo_2_idx` (`profesor` ASC),
  CONSTRAINT `fk_grupo_1`
    FOREIGN KEY (`materia`)
    REFERENCES `mydb`.`materia` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupo_2`
    FOREIGN KEY (`profesor`)
    REFERENCES `mydb`.`usuario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`prueba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prueba` (
  `codigo` INT NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `cuestionario` INT NOT NULL,
  `fecha_aplicacion` DATETIME NOT NULL,
  `duracion` INT NOT NULL,
  `grupo` INT NOT NULL,
  `usuario_programador` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_prueba_1_idx` (`cuestionario` ASC),
  INDEX `fk_prueba_2_idx` (`grupo` ASC),
  INDEX `fk_prueba_3_idx` (`usuario_programador` ASC),
  CONSTRAINT `fk_prueba_1`
    FOREIGN KEY (`cuestionario`)
    REFERENCES `mydb`.`cuestionario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prueba_2`
    FOREIGN KEY (`grupo`)
    REFERENCES `mydb`.`grupo` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prueba_3`
    FOREIGN KEY (`usuario_programador`)
    REFERENCES `mydb`.`usuario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`evaluacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`evaluacion` (
  `codigo` INT NOT NULL,
  `prueba` INT NOT NULL,
  `estudiante` INT NOT NULL,
  `calificacion` DOUBLE NOT NULL,
  `valor_aprobacion` DOUBLE NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_evaluacion_1_idx` (`prueba` ASC),
  INDEX `fk_evaluacion_2_idx` (`estudiante` ASC),
  CONSTRAINT `fk_evaluacion_1`
    FOREIGN KEY (`prueba`)
    REFERENCES `mydb`.`prueba` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evaluacion_2`
    FOREIGN KEY (`estudiante`)
    REFERENCES `mydb`.`usuario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`area_conocimiento_x_pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`area_conocimiento_x_pregunta` (
  `area_conocimiento` INT NOT NULL,
  `pregunta` INT NOT NULL,
  INDEX `fk_area_conocimiento_x_pregunta_1_idx` (`area_conocimiento` ASC),
  INDEX `fk_area_conocimiento_x_pregunta_2_idx` (`pregunta` ASC),
  PRIMARY KEY (`area_conocimiento`, `pregunta`),
  CONSTRAINT `fk_area_conocimiento_x_pregunta_1`
    FOREIGN KEY (`area_conocimiento`)
    REFERENCES `mydb`.`area_conocimiento` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_area_conocimiento_x_pregunta_2`
    FOREIGN KEY (`pregunta`)
    REFERENCES `mydb`.`pregunta` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estudiante_x_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estudiante_x_grupo` (
  `codigo` INT NOT NULL,
  `estudiante` INT NOT NULL,
  `grupo` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_estudiante_x_grupo_1_idx` (`estudiante` ASC),
  INDEX `fk_estudiante_x_grupo_2_idx` (`grupo` ASC),
  CONSTRAINT `fk_estudiante_x_grupo_1`
    FOREIGN KEY (`estudiante`)
    REFERENCES `mydb`.`usuario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiante_x_grupo_2`
    FOREIGN KEY (`grupo`)
    REFERENCES `mydb`.`grupo` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`respuesta_x_pregunta_x_cuestionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`respuesta_x_pregunta_x_cuestionario` (
  `codigo` INT NOT NULL,
  `pregunta_x_cuestionario` INT NOT NULL,
  `respuesta` INT NOT NULL,
  `indice` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_respuesta_x_pregunta_x_cuestionario_1_idx` (`pregunta_x_cuestionario` ASC),
  INDEX `fk_respuesta_x_pregunta_x_cuestionario_2_idx` (`respuesta` ASC),
  CONSTRAINT `fk_respuesta_x_pregunta_x_cuestionario_1`
    FOREIGN KEY (`pregunta_x_cuestionario`)
    REFERENCES `mydb`.`pregunta_x_cuestionario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_respuesta_x_pregunta_x_cuestionario_2`
    FOREIGN KEY (`respuesta`)
    REFERENCES `mydb`.`respuesta` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`respuesta_estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`respuesta_estudiante` (
  `codigo` INT NOT NULL,
  `evaluacion` INT NOT NULL,
  `respuesta` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_evaluacion_x_pregunta_x_respuesta_1_idx` (`evaluacion` ASC),
  INDEX `fk_evaluacion_x_pregunta_x_respuesta_3_idx` (`respuesta` ASC),
  CONSTRAINT `fk_evaluacion_x_pregunta_x_respuesta_1`
    FOREIGN KEY (`evaluacion`)
    REFERENCES `mydb`.`evaluacion` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evaluacion_x_pregunta_x_respuesta_3`
    FOREIGN KEY (`respuesta`)
    REFERENCES `mydb`.`respuesta` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cuestionario_variacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cuestionario_variacion` (
  `codigo` INT NOT NULL,
  `cuestionario_padre` INT NOT NULL,
  `fecha_creacion` TIMESTAMP NOT NULL,
  `autor` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_variacion_cuestionario_1_idx` (`cuestionario_padre` ASC),
  INDEX `fk_cuestionario_variacion_1_idx` (`autor` ASC),
  CONSTRAINT `fk_variacion_cuestionario_1`
    FOREIGN KEY (`cuestionario_padre`)
    REFERENCES `mydb`.`cuestionario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cuestionario_variacion_1`
    FOREIGN KEY (`autor`)
    REFERENCES `mydb`.`usuario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
